spring.application.name=ms-reservas
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/reservas;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:reservas}
spring.rabbitmq.password=${RABBIT_PASSWORD:reservas-demo}
spring.rabbitmq.connection-timeout=3s
spring.rabbitmq.requested-heartbeat=10s
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.default-requeue-rejected=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.rabbit.enabled=true
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%thread] %logger{25} - %msg%n
disponibilidad.url=${DISPONIBILIDAD_URL:http://localhost:8081}
