spring.application.name=ms-disponibilidad
server.port=${PORT:8081}
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/disponibilidad;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:reservas}
spring.rabbitmq.password=${RABBIT_PASSWORD:reservas-demo}
spring.rabbitmq.connection-timeout=3s
spring.rabbitmq.requested-heartbeat=10s
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.default-requeue-rejected=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.rabbit.enabled=false
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%thread] %logger{25} - %msg%n
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:common}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_CLIENT_ID:reservas-api}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
